# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-29 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelXP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('XPAward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Slot', models.TextField()),
                ('SubSlot', models.TextField()),
                ('Level', models.IntegerField(default=0)),
                ('Book', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monsters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Race', models.TextField()),
                ('SubRace', models.TextField()),
                ('Book', models.TextField()),
                ('Origin', models.TextField()),
                ('Type', models.TextField()),
                ('Keyword', models.TextField()),
                ('Level', models.IntegerField(default=0)),
                ('Class', models.TextField()),
                ('Threat', models.TextField()),
                ('Habitat', models.TextField()),
                ('Social', models.TextField()),
                ('AllyGroups', models.TextField()),
            ],
        ),
    ]
