# cfb_uwsgi.ini file
[uwsgi]

chdir = /home/testor/CFB_Proj/CFB_Site
module = app_proj.wsgi:application
home = /home/testor/CFB_Proj/v2

master = true
processes = 2
vacuum = true
plugins = python3

socket=/home/testor/CFB_Proj/CFB_Site/app_proj/server/cfb_socket.sock
chmod-socket = 666
#chown-socket = www-data
uid = www-data
gid = www-data

